services:
  scooze:
    # image: "arcavios/scooze:latest"
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - MONGO_HOST=mongodb
    ports:
      - "8000:8000"
  mongodb:
    image: "mongo:latest"
    ports:
      - "27017:27017"
