site_name: scooze

theme:
    name: material
    #   custom_dir: 'docs/theme'
    palette:
        - media: "(prefers-color-scheme: light)"
          scheme: default
          primary: green
          accent: green
          toggle:
              icon: material/lightbulb-outline
              name: "Switch to dark mode"
        - media: "(prefers-color-scheme: dark)"
          scheme: slate
          primary: green
          accent: green
          toggle:
              icon: material/lightbulb
              name: "Switch to light mode"
    features: # TODO(#153): I don't know what any of these do
        - content.tabs.link
        - content.code.annotate
        - content.code.copy
        - announce.dismiss
        - navigation.tabs
#   logo: 'logo-white.svg'
#   favicon: 'favicon.png'

repo_name: arcavios/scooze
repo_url: https://github.com/arcavios/scooze

# https://www.mkdocs.org/user-guide/configuration/#validation
validation:
    nav:
        omitted_files: warn # default: info
        not_found: warn # default: warn
        absolute_links: info # default: info
    links:
        not_found: warn # default: warn
        absolute_links: warn # default: info
        unrecognized_links: warn # default: info

nav:
    - Get Started:
          - Introduction to scooze: index.md
          - Installation: installation.md
          - Setup: setup.md
          - Contributing: contributing.md
          - Changelog: changelog.md
    - API Documentation:
          - Models:
                - Card: models/card.md
                - Deck: models/deck.md
                - Base Models: models/base_models.md
          - Data Classes:
                - Card: dataclasses/card.md
                - Deck: dataclasses/deck.md
          - Database Interface:
                - Python: db_interface/scooze_api.md
                - REST API:
                      - Card: db_interface/rest/card.md
                      - Deck: db_interface/rest/deck.md
          - Extras:
                - Utils: extras/utils.md
                - Catalogs: extras/catalogs.md
                - Bulkdata: extras/bulkdata.md
                - Command Line Interface: extras/cli.md
    - Arcavios Team: people.md

plugins:
    - search
    - mkdocstrings:
          handlers:
              python:
                  import:
                      - https://docs.python.org/3/objects.inv
                  paths: [src]
                  options:
                      docstring_options:
                          ignore_init_summary: true
                      heading_level: 2
                      inherited_members: true
                      merge_init_into_class: false
                      members_order: source
                      separate_signature: false
                      show_root_heading: true
                      show_root_full_path: true
                      show_source: false
                      show_signature_annotations: true
                      show_symbol_type_heading: true
                      show_symbol_type_toc: true
                      signature_crossrefs: true
                      summary: true

markdown_extensions:
    - admonition
    - pymdownx.details
    - pymdownx.highlight:
          anchor_linenums: true
          line_spans: __span
          pygments_lang_class: true
    - pymdownx.inlinehilite
    - pymdownx.snippets
    - pymdownx.superfences
    - toc:
          permalink: true
