name: Pytest

on: [push]


# https://github.com/matrix-org/setup-python-poetry

jobs:
  test:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11", "3.12"]

    steps:
      - name: Install and configure Poetry
        uses: matrix-org/setup-python-poetry@v1
        with:
          python-version: ${{ matrix.python-version }}
          poetry-version: 1.5.1 # TODO: matrix this?

      - name: Test with pytest
        run: pytest tests/
