#  0 7 * * 1

# TODO: before I can implement this workflow I need to be able to get logs
# Add logging to our CLI commands

# TODO: pseudocode
# pip install scooze
# scooze load cards --all
# check the size of the log, maybe report some of the stuff?

name: Scryfall Bulkdata Validation

on:
    [push]
    # Every Monday at 07:00 UTC
    # schedule:
    #     - cron: "0 7 * * 1"

jobs:
    linting:
        runs-on: ubuntu-latest
        steps:
            - run: |
                  docker info
                  docker ps -a
