#  0 7 * * 1

# TODO: before I can implement this workflow I need to be able to get logs
# Add logging to our CLI commands

# TODO: pseudocode
# pip install scooze
# scooze load cards --all
# check the size of the log, maybe report some of the stuff?

name: Scryfall Bulkdata Validation

on:
    [push]
    # Every Monday at 07:00 UTC
    # schedule:
    #     - cron: "0 7 * * 1"

jobs:
    setup-matrix:
        runs-on: ubuntu-latest
        outputs:
            matrix: ${{ steps.setup-matrix.outputs.matrix }}
        steps:
            - id: setup-matrix
              uses: druzsan/setup-matrix@v2
              with:
                  # Use | to preserve valid YAML syntax
                  matrix: |
                      os: ['ubuntu-latest'] # 'macos-latest'
                      python-version: ['3.11', '3.12']
    setup-python:
        needs: setup-matrix
        strategy:
            fail-fast: true
            matrix: ${{ fromJson(needs.setup-matrix.outputs.matrix) }}
        runs-on: ${{ matrix.os }}
        steps:
            #----------------------------------------------
            #       check-out repo and set-up python
            #----------------------------------------------
            - uses: actions/checkout@v4
            - uses: actions/setup-python@v5
              with:
                  python-version: ${{ matrix.python-version }}
            #----------------------------------------------
            #        load pip cache if cache exists
            #----------------------------------------------
            - uses: actions/cache@v4
              with:
                  path: ~/.cache/pip
                  key: ${{ runner.os }}-pip
                  restore-keys: ${{ runner.os }}-pip
    do-a-thing:
        needs:
            - setup-matrix
            - setup-python
        runs-on: ubuntu-latest
        steps:
            - run: |
                  docker info
                  docker ps -a
    pytest:
        needs:
            - setup-matrix
        strategy:
            fail-fast: true
            matrix: ${{ fromJson(needs.setup-matrix.outputs.matrix) }}
        runs-on: ${{ matrix.os }}
        steps:
            #----------------------------------------------
            #       check-out repo and set up python
            #----------------------------------------------
            - name: Check out repository
              uses: actions/checkout@v4
            - name: Set up Python ${{ matrix.python-version }}
              id: setup-python
              uses: actions/setup-python@v5
              with:
                  python-version: ${{ matrix.python-version }}
            #----------------------------------------------
            #  -----  install & configure poetry  -----
            #----------------------------------------------
            - name: Install Poetry
              uses: snok/install-poetry@v1
              with:
                  # version: ${{ matrix.poetry-version }}
                  virtualenvs-create: true
                  virtualenvs-in-project: true
            #----------------------------------------------
            #       load cached venv if cache exists
            #----------------------------------------------
            - name: Load cached venv
              id: cached-poetry-dependencies
              uses: actions/cache@v4
              with:
                  path: .venv
                  key: venv-${{ runner.os }}-${{ steps.setup-python.outputs.python-version }}-${{ hashFiles('**/poetry.lock') }}
            #----------------------------------------------
            # install dependencies if cache does not exist
            #----------------------------------------------
            - name: Install dependencies
              if: steps.cached-poetry-dependencies.outputs.cache-hit != 'true'
              run: poetry install --no-interaction --no-root
            #----------------------------------------------
            # install your root project, if required
            #----------------------------------------------
            - name: Install library
              run: poetry install --no-interaction
            #----------------------------------------------
            #    add matrix specifics and run test suite
            #----------------------------------------------
            - name: Load Scryfall bulkdata
              run: |
                  source .venv/bin/activate
                  scooze setup docker
                  scooze load cards --test
