name: Deploy to test.pypi.org

# https://github.com/marketplace/actions/publish-python-poetry-package
# TODO: this is a test

on: [push]
  # push:
  #   tags:
  #     - "v*.*.*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build and publish to pypi
        uses: JRubics/poetry-publish@v1.17
        with:
          python_version: 3.11
          pypi_token: ${{ secrets.TEST_PYPI_TOKEN }}
          repository_name: "test.pypi"
          repository_url: "https://test.pypi.org/legacy/"
